import Foundation

enum DemoData {
    static let exercises: [Exercise] = [
        Exercise(name: "Wall Push-up", muscleGroup: .chest, primaryMuscles: ["Chest"], secondaryMuscles: ["Triceps"], equipment: [.noEquipment], level: .easy, videoName: "wall_push_up", instructions: ["Stand facing a wall.", "Place hands on the wall.", "Lower chest slowly.", "Push back."], mistakes: ["Standing too close", "Rushing reps"]),
        Exercise(name: "Incline Push-up", muscleGroup: .chest, primaryMuscles: ["Chest"], secondaryMuscles: ["Triceps", "Front Delts"], equipment: [.noEquipment, .household], level: .easy, videoName: "incline_push_up", instructions: ["Hands on a sofa or table.", "Keep body straight.", "Lower slowly.", "Press up."], mistakes: ["Dropping hips", "Half reps"]),
        Exercise(name: "Push-up", muscleGroup: .chest, primaryMuscles: ["Chest"], secondaryMuscles: ["Triceps", "Core"], equipment: [.noEquipment], level: .medium, videoName: "push_up", instructions: ["Hands slightly wider than shoulders.", "Keep body straight.", "Lower chest near floor.", "Press up."], mistakes: ["Hips high", "Elbows too wide"]),
        Exercise(name: "Decline Push-up", muscleGroup: .chest, primaryMuscles: ["Upper Chest"], secondaryMuscles: ["Shoulders", "Triceps"], equipment: [.noEquipment, .household], level: .hard, videoName: "decline_push_up", instructions: ["Feet elevated.", "Body straight.", "Lower with control.", "Press up."], mistakes: ["Sagging hips", "Too much speed"]),
        Exercise(name: "Incline Dumbbell Press", muscleGroup: .chest, primaryMuscles: ["Chest"], secondaryMuscles: ["Triceps"], equipment: [.dumbbells, .bench], level: .medium, videoName: "incline_dumbbell_press", instructions: ["Lie on an incline bench.", "Lower dumbbells with control.", "Press up.", "Keep shoulders stable."], mistakes: ["Bouncing reps", "Overarching back"]),

        Exercise(name: "Superman", muscleGroup: .back, primaryMuscles: ["Lower Back"], secondaryMuscles: ["Glutes"], equipment: [.noEquipment], level: .easy, videoName: "superman", instructions: ["Lie face down.", "Lift arms and legs.", "Pause.", "Lower slowly."], mistakes: ["Lifting too high", "Neck tension"]),
        Exercise(name: "Reverse Snow Angels", muscleGroup: .back, primaryMuscles: ["Upper Back", "Rear Delts"], secondaryMuscles: ["Lower Traps"], equipment: [.noEquipment], level: .easy, videoName: "reverse_snow_angels", instructions: ["Lie face down.", "Lift chest slightly.", "Sweep arms overhead.", "Return slowly."], mistakes: ["Shrugging", "Rushing"]),
        Exercise(name: "Backpack Bent-over Row", muscleGroup: .back, primaryMuscles: ["Lats", "Upper Back"], secondaryMuscles: ["Biceps"], equipment: [.household], level: .medium, videoName: "backpack_bent_over_row", instructions: ["Hinge forward.", "Pull backpack to stomach.", "Squeeze back.", "Lower slowly."], mistakes: ["Rounding back", "Using momentum"]),
        Exercise(name: "Backpack Romanian Deadlift", muscleGroup: .back, primaryMuscles: ["Hamstrings", "Glutes", "Lower Back"], secondaryMuscles: ["Core"], equipment: [.household], level: .medium, videoName: "backpack_romanian_deadlift", instructions: ["Hold backpack close.", "Push hips back.", "Keep spine neutral.", "Stand tall."], mistakes: ["Rounding spine", "Squatting instead of hinging"]),
        Exercise(name: "Romanian Deadlift", muscleGroup: .back, primaryMuscles: ["Hamstrings", "Glutes", "Lower Back"], secondaryMuscles: ["Upper Back"], equipment: [.dumbbells], level: .medium, videoName: "romanian_deadlift", instructions: ["Hold weights close.", "Hinge at hips.", "Feel hamstrings stretch.", "Stand tall."], mistakes: ["Rounding back", "Weights too far away"]),
        Exercise(name: "Door Towel Row", muscleGroup: .back, primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Biceps"], equipment: [.household], level: .hard, videoName: "door_towel_row", instructions: ["Use a strong door only.", "Lean back.", "Pull chest forward.", "Lower controlled."], mistakes: ["Unsafe door", "Jerking"]),
        Exercise(name: "Pull-up", muscleGroup: .back, primaryMuscles: ["Lats"], secondaryMuscles: ["Biceps"], equipment: [.pullUpBar], level: .hard, videoName: "pull_up", instructions: ["Grip the bar.", "Pull chest upward.", "Lower with control.", "Keep body stable."], mistakes: ["Swinging", "Half reps"]),

        Exercise(name: "Wall Angels", muscleGroup: .shoulders, primaryMuscles: ["Rear Delts", "Lower Traps"], secondaryMuscles: ["Shoulders"], equipment: [.noEquipment], level: .easy, videoName: "wall_angels", instructions: ["Back to wall.", "Ribs down.", "Slide arms up and down.", "Stay controlled."], mistakes: ["Arching back", "Forcing range"]),
        Exercise(name: "Pike Push-up", muscleGroup: .shoulders, primaryMuscles: ["Shoulders"], secondaryMuscles: ["Triceps"], equipment: [.noEquipment], level: .medium, videoName: "pike_push_up", instructions: ["Hips high.", "Head toward floor.", "Press back.", "Control."], mistakes: ["Wrong angle", "Short reps"]),
        Exercise(name: "Backpack Shoulder Press", muscleGroup: .shoulders, primaryMuscles: ["Shoulders"], secondaryMuscles: ["Triceps"], equipment: [.household], level: .medium, videoName: "backpack_shoulder_press", instructions: ["Hold backpack at chest.", "Press overhead.", "Lower slowly.", "Brace core."], mistakes: ["Leaning back", "Rushing"]),
        Exercise(name: "Shoulder Press", muscleGroup: .shoulders, primaryMuscles: ["Shoulders"], secondaryMuscles: ["Triceps"], equipment: [.dumbbells], level: .hard, videoName: "shoulder_press", instructions: ["Weights at shoulders.", "Press overhead.", "Lower slowly.", "Brace core."], mistakes: ["Arching back", "Pressing forward"]),

        Exercise(name: "Backpack Curl", muscleGroup: .biceps, primaryMuscles: ["Biceps"], secondaryMuscles: ["Forearms"], equipment: [.household], level: .easy, videoName: "backpack_curl", instructions: ["Hold backpack.", "Curl with elbows still.", "Squeeze.", "Lower slowly."], mistakes: ["Swinging", "Moving elbows"]),
        Exercise(name: "Dumbbell Curl", muscleGroup: .biceps, primaryMuscles: ["Biceps"], secondaryMuscles: ["Forearms"], equipment: [.dumbbells], level: .medium, videoName: "dumbbell_curl", instructions: ["Elbows close.", "Curl up.", "Pause.", "Lower slowly."], mistakes: ["Swinging", "Half reps"]),
        Exercise(name: "Close-Grip Push-up", muscleGroup: .triceps, primaryMuscles: ["Triceps"], secondaryMuscles: ["Chest"], equipment: [.noEquipment], level: .medium, videoName: "close_grip_push_up", instructions: ["Hands under shoulders.", "Elbows near body.", "Lower.", "Press up."], mistakes: ["Elbows flaring", "Dropping hips"]),
        Exercise(name: "Chair Triceps Dip", muscleGroup: .triceps, primaryMuscles: ["Triceps"], secondaryMuscles: ["Shoulders", "Chest"], equipment: [.household, .noEquipment], level: .hard, videoName: "chair_triceps_dip", instructions: ["Hands on chair.", "Lower hips.", "Elbows back.", "Press up."], mistakes: ["Unstable chair", "Shoulders shrugged"]),

        Exercise(name: "Bodyweight Squat", muscleGroup: .legs, primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings"], equipment: [.noEquipment], level: .easy, videoName: "bodyweight_squat", instructions: ["Feet shoulder-width.", "Sit hips back.", "Chest up.", "Stand tall."], mistakes: ["Knees inward", "Heels lifting"]),
        Exercise(name: "Reverse Lunge", muscleGroup: .legs, primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings"], equipment: [.noEquipment], level: .medium, videoName: "reverse_lunge", instructions: ["Step back.", "Lower knees.", "Push front foot.", "Switch."], mistakes: ["Short step", "Knee collapsing"]),
        Exercise(name: "Bulgarian Split Squat", muscleGroup: .legs, primaryMuscles: ["Quads", "Glutes"], secondaryMuscles: ["Hamstrings"], equipment: [.household, .noEquipment], level: .hard, videoName: "bulgarian_split_squat", instructions: ["Back foot on chair.", "Lower down.", "Drive up.", "Keep balance."], mistakes: ["Foot too close", "Leaning too far"]),
        Exercise(name: "Glute Bridge", muscleGroup: .glutes, primaryMuscles: ["Glutes"], secondaryMuscles: ["Hamstrings"], equipment: [.noEquipment], level: .easy, videoName: "glute_bridge", instructions: ["Lie on back.", "Feet planted.", "Lift hips.", "Squeeze glutes."], mistakes: ["Arching back", "Feet too far"]),
        Exercise(name: "Single-Leg Glute Bridge", muscleGroup: .glutes, primaryMuscles: ["Glutes"], secondaryMuscles: ["Hamstrings"], equipment: [.noEquipment], level: .hard, videoName: "single_leg_glute_bridge", instructions: ["One foot planted.", "Other leg extended.", "Lift hips.", "Control down."], mistakes: ["Hips rotating", "Pushing through toes"]),

        Exercise(name: "Dead Bug", muscleGroup: .abs, primaryMuscles: ["Core"], secondaryMuscles: ["Hip Flexors"], equipment: [.noEquipment], level: .easy, videoName: "dead_bug", instructions: ["Lie on back.", "Arms and legs up.", "Lower opposite limbs.", "Switch."], mistakes: ["Back arching", "Moving fast"]),
        Exercise(name: "Plank", muscleGroup: .abs, primaryMuscles: ["Core"], secondaryMuscles: ["Shoulders", "Glutes"], equipment: [.noEquipment], level: .medium, videoName: "plank", instructions: ["Forearms down.", "Body straight.", "Brace.", "Breathe."], mistakes: ["Hips high", "Back sagging"]),
        Exercise(name: "Side Plank", muscleGroup: .abs, primaryMuscles: ["Obliques"], secondaryMuscles: ["Shoulders", "Glutes"], equipment: [.noEquipment], level: .hard, videoName: "side_plank", instructions: ["Elbow under shoulder.", "Lift hips.", "Hold straight line.", "Switch side."], mistakes: ["Hips dropping", "Shoulder shrugging"]),

        Exercise(name: "Child's Pose", muscleGroup: .mobility, primaryMuscles: ["Back Mobility"], secondaryMuscles: ["Hips"], equipment: [.noEquipment], level: .easy, videoName: "childs_pose", instructions: ["Kneel.", "Sit hips back.", "Reach forward.", "Breathe."], mistakes: ["Forcing shoulders", "Holding breath"]),
        Exercise(name: "Quadruped Thoracic Rotation", muscleGroup: .mobility, primaryMuscles: ["Upper Back Mobility"], secondaryMuscles: ["Core"], equipment: [.noEquipment], level: .medium, videoName: "quadruped_thoracic_rotation", instructions: ["On hands and knees.", "Hand behind head.", "Rotate elbow up.", "Return."], mistakes: ["Rotating hips", "Forcing neck"])
    ]

    static var sampleWorkout: WorkoutPlan {
        WeeklyPlanGenerator.generatePlan(from: exercises, assessment: .defaultValue).first ??
        WorkoutPlan(name: "Home Strength", focus: "Strength", exercises: [], estimatedMinutes: 35)
    }

    static let history: [WorkoutHistory] = []
}
